from abc import ABC, abstractmethod
from typing import Any, Dict, List
from src.brain.node.nodeDTOs import ThoughtDTO, NodeReasoningResultDTO
from src.brain.node.scratchPad import ScratchPad
from src.brain.node.chainOfThought import ChainOfThought
from src.brain.node.nodeProcessingEngine import nodeProcessingEngine
from src.body.perception.perceptionDTOs import PerceptionBundleDTO
from src.body.perception.perceptionFormatter import PerceptionPromptFormatter

class CorticalColumn(ABC):
    def __init__(self, column_id: int, memory_engine: Any, emotion_handler: Any, scheduler: Any):
        """
        Base class representing a specialized cortical column in the swarm.
        """
        self.column_id = column_id
        self.memory = memory_engine
        self.emotion = emotion_handler
        self.scheduler = scheduler
        self.scratchpad = ScratchPad()
        self.chain = ChainOfThought()
        self.engine = nodeProcessingEngine(
            memory_engine=self.memory,
            emotion_handler=self.emotion,
            scratchpad=self.scratchpad,
            chain_of_thought=self.chain,
            reasoning_scheduler=self.scheduler
        )
        self.perception_formatter = PerceptionPromptFormatter()

    @property
    @abstractmethod
    def system_prompt(self) -> str:
        """
        Custom instructions defining the role and thinking perspective of this column.
        """
        pass

    @property
    @abstractmethod
    def search_policy(self) -> Dict[str, Any]:
        """
        Custom decoder settings (e.g. temperature, top_p, max_new_tokens).
        """
        pass

    def retrieve_context(self, perception: Any) -> List[Any]:
        """
        Define memory and emotion retrieval priorities specific to this column.
        """
        raw = self.memory.retrieve(self._memory_query(perception), limit=3)
        return list(getattr(raw, "memories", raw))

    def activate(self, perception: Any, working_history: List[ThoughtDTO] = None) -> NodeReasoningResultDTO:
        formatted_perception = self._format_for_reasoning(perception)
        return self.engine.process(
            formatted_perception,
            seed_thoughts=working_history or [],
            memories=self.retrieve_context(perception)
        )

    def _format_for_reasoning(self, perception: Any) -> str:
        if isinstance(perception, PerceptionBundleDTO):
            formatted_perception = self.perception_formatter.format_bundle(perception)
        else:
            formatted_perception = str(perception)

        return (
            f"Specialty Instruction: {self.system_prompt}\n"
            f"{formatted_perception}"
        )

    def _memory_query(self, perception: Any) -> str:
        if isinstance(perception, PerceptionBundleDTO):
            return self.perception_formatter.format_bundle(perception)
        return str(perception)



class AnalyticalColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are an Analytical Cortical Column. Focus purely on logic, evidence, and mathematical correctness."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.1, "top_p": 0.85, "max_new_tokens": 128}


class CreativeColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Creative Cortical Column. Brainstorm analogies, lateral hypotheses, and novel connection paths."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.85, "top_p": 0.95, "max_new_tokens": 160}


class RiskColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Risk & Safety Column. Focus on identifying failure modes, edge-case risks, and system instability."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.2, "top_p": 0.90, "max_new_tokens": 128}


class VerificationColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Verification Column. Audit the thoughts generated by other columns for contradictions and factual errors."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.05, "top_p": 0.80, "max_new_tokens": 96}
