from abc import ABC, abstractmethod
from typing import Any, Dict, List
from src.brain.node.nodeDTOs import ThoughtDTO, NodeReasoningResultDTO
from src.brain.node.scratchPad import ScratchPad
from src.brain.node.chainOfThought import ChainOfThought
from src.brain.node.nodeProcessingEngine import nodeProcessingEngine

class CorticalColumn(ABC):
    def __init__(self, column_id: int, memory_engine: Any, emotion_handler: Any, scheduler: Any):
        """
        Base class representing a specialized cortical column in the swarm.
        """
        self.column_id = column_id
        self.memory = memory_engine
        self.emotion = emotion_handler
        self.scheduler = scheduler
        self.scratchpad = ScratchPad()
        self.chain = ChainOfThought()
        self.engine = nodeProcessingEngine(
            memory_engine=self.memory,
            emotion_handler=self.emotion,
            scratchpad=self.scratchpad,
            chain_of_thought=self.chain,
            reasoning_scheduler=self.scheduler
        )

    @property
    @abstractmethod
    def system_prompt(self) -> str:
        """
        Custom instructions defining the role and thinking perspective of this column.
        """
        pass

    @property
    @abstractmethod
    def search_policy(self) -> Dict[str, Any]:
        """
        Custom decoder settings (e.g. temperature, top_p, max_new_tokens).
        """
        pass

    def retrieve_context(self, perception: Any) -> List[Any]:
        """
        Define memory and emotion retrieval priorities specific to this column.
        """
        raw = self.memory.retrieve(perception, limit=3)
        return list(getattr(raw, "memories", raw))

    def activate(self, perception: Any, working_history: List[ThoughtDTO] = None) -> NodeReasoningResultDTO:
        # Pre-load context and execute node loop
        memories = self.retrieve_context(perception)
        
        self.scratchpad.clear()
        self.chain.reset()
        
        # Format structured sensory observations nicely for the reasoning workspace
        if isinstance(perception, dict) and "observations" in perception:
            obs_list = []
            for dev, val in perception["observations"].items():
                # Present a clean preview representing the raw observation data
                if isinstance(val, bytes):
                    preview = f"<Raw Bytes: Length {len(val)}>"
                else:
                    preview = str(val)
                obs_list.append(f"- {dev}: {preview}")
            
            obs_str = "\n".join(obs_list)
            formatted_perception = (
                f"Query/Problem: {perception.get('query')}\n"
                f"Current Sensory Observations:\n{obs_str}"
            )
        else:
            formatted_perception = str(perception)
        
        # Format the sensory input alongside the column's specialized system prompt
        self.scratchpad.initialize(
            perception=f"[Specialty Instruction: {self.system_prompt}] Perception:\n{formatted_perception}",
            memory=memories,
            emotion=self.emotion.current_emotion() if hasattr(self.emotion, "current_emotion") else None
        )
        
        if working_history:
            for t in working_history:
                self.scratchpad.append_thought(t)
                
        # Run node reasoning
        return self.engine.process(formatted_perception)



class AnalyticalColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are an Analytical Cortical Column. Focus purely on logic, evidence, and mathematical correctness."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.1, "top_p": 0.85, "max_new_tokens": 128}


class CreativeColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Creative Cortical Column. Brainstorm analogies, lateral hypotheses, and novel connection paths."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.85, "top_p": 0.95, "max_new_tokens": 160}


class RiskColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Risk & Safety Column. Focus on identifying failure modes, edge-case risks, and system instability."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.2, "top_p": 0.90, "max_new_tokens": 128}


class VerificationColumn(CorticalColumn):
    @property
    def system_prompt(self) -> str:
        return "You are a Verification Column. Audit the thoughts generated by other columns for contradictions and factual errors."
        
    @property
    def search_policy(self) -> Dict[str, Any]:
        return {"temperature": 0.05, "top_p": 0.80, "max_new_tokens": 96}
