from typing import Optional
from src.brain.node.nodeDTOs import NodeReasoningResultDTO

class Decoder:
    """
    The Final Decoder is the only component responsible for producing human-readable outputs.
    It takes the Brain's reasoning result (NodeReasoningResultDTO) and translates it
    into natural language text for the user.
    """

    def decode(self, reasoning_result: NodeReasoningResultDTO) -> str:
        """
        Converts the Brain's final reasoning/decision into a natural language response.
        """
        if not reasoning_result:
            return "No reasoning output generated by the cognitive layer."

        # If the brain reached a structured final decision:
        if reasoning_result.decision:
            return reasoning_result.decision

        # Fallback to the latest reasoning thought body:
        if reasoning_result.thought_history:
            return reasoning_result.thought_history[-1].thought_body

        return "I am processing the sensory inputs but did not formulate a final thought."
