from __future__ import annotations

import tempfile
import wave
from array import array
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Optional, Union
from uuid import uuid4

try:
    from kokoro import KPipeline
except ImportError:
    KPipeline = None

from src.swarm.swarmDTOs import MothershipResponseDTO
from src.user.blocks.output_blocks import ShivaOutputBlock
from src.user.constants import OutputFormat


OutputBlockLike = Union[ShivaOutputBlock, OutputFormat, str, Dict[str, Any], None]


@dataclass(slots=True)
class DecoderOutputDTO:
    format: OutputFormat
    text: str
    payload: str
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> Dict[str, Any]:
        return {
            "format": self.format.value,
            "text": self.text,
            "payload": self.payload,
            "metadata": dict(self.metadata),
        }


class Decoder:
    def __init__(
        self,
        tts_output_dir: Optional[str] = None,
        tts_voice: str = "af_heart",
        tts_language: str = "a",
        tts_speed: float = 1.0,
        tts_sample_rate: int = 24000,
    ) -> None:
        self.tts_output_dir = Path(tts_output_dir or tempfile.gettempdir()) / "shiva_tts"
        self.tts_voice = tts_voice
        self.tts_language = tts_language
        self.tts_speed = tts_speed
        self.tts_sample_rate = tts_sample_rate
        self._tts_pipeline: Any = None

    def decode(self, response: MothershipResponseDTO) -> str:
        return self._extract_text(response)

    def decode_for_output_block(
        self,
        response: MothershipResponseDTO,
        output_block: OutputBlockLike = None,
    ) -> DecoderOutputDTO:
        text = self._extract_text(response)
        output_format = self._resolve_output_format(output_block)

        if output_format == OutputFormat.TEXT:
            return DecoderOutputDTO(
                format=OutputFormat.TEXT,
                text=text,
                payload=text,
                metadata={"delivery": "text"},
            )

        wav_path = self._text_to_speech(text)
        return DecoderOutputDTO(
            format=OutputFormat.VOICE,
            text=text,
            payload=str(wav_path),
            metadata={
                "delivery": "voice",
                "provider": "kokoro",
                "voice": self.tts_voice,
                "language": self.tts_language,
                "speed": self.tts_speed,
                "sample_rate": self.tts_sample_rate,
                "content_type": "audio/wav",
            },
        )

    def _extract_text(self, response: MothershipResponseDTO) -> str:
        if not response:
            return "No reasoning output generated by the cognitive layer."

        if response.decision:
            return response.decision

        if response.reasoning_summary:
            return response.reasoning_summary

        return "I am processing the sensory inputs but did not formulate a final thought."

    def _resolve_output_format(self, output_block: OutputBlockLike) -> OutputFormat:
        if output_block is None:
            return OutputFormat.TEXT

        if isinstance(output_block, ShivaOutputBlock):
            return output_block.output_format

        if isinstance(output_block, OutputFormat):
            return output_block

        if isinstance(output_block, str):
            return OutputFormat(output_block)

        if isinstance(output_block, dict):
            raw_format = (
                output_block.get("output_format")
                or output_block.get("format")
                or output_block.get("config", {}).get("format")
            )
            if raw_format is None:
                return OutputFormat.TEXT
            return OutputFormat(raw_format)

        raise TypeError("output_block must be a ShivaOutputBlock, OutputFormat, string, dictionary, or None.")

    def _text_to_speech(self, text: str) -> Path:
        if not text or not text.strip():
            raise ValueError("Cannot convert empty text to speech.")

        pipeline = self._get_tts_pipeline()
        self.tts_output_dir.mkdir(parents=True, exist_ok=True)
        wav_path = self.tts_output_dir / f"shiva_tts_{uuid4().hex}.wav"

        audio_samples = array("h")
        for kokoro_item in pipeline(
            text,
            voice=self.tts_voice,
            speed=self.tts_speed,
        ):
            audio_chunk = self._extract_audio_chunk(kokoro_item)
            audio_samples.extend(self._to_pcm16_samples(audio_chunk))

        if not audio_samples:
            raise RuntimeError("Kokoro TTS did not generate any audio samples.")

        self._write_wav(wav_path, audio_samples)
        return wav_path

    def _get_tts_pipeline(self) -> Any:
        if KPipeline is None:
            raise RuntimeError(
                "Kokoro TTS is required for voice output. Install the 'kokoro' package "
                "before selecting a VOICE output block."
            )

        if self._tts_pipeline is None:
            self._tts_pipeline = KPipeline(lang_code=self.tts_language)
        return self._tts_pipeline

    def _extract_audio_chunk(self, kokoro_item: Any) -> Any:
        if isinstance(kokoro_item, tuple) and kokoro_item:
            return kokoro_item[-1]
        return kokoro_item

    def _to_pcm16_samples(self, audio_chunk: Any) -> array:
        if hasattr(audio_chunk, "detach"):
            audio_chunk = audio_chunk.detach()
        if hasattr(audio_chunk, "cpu"):
            audio_chunk = audio_chunk.cpu()
        if hasattr(audio_chunk, "numpy"):
            audio_chunk = audio_chunk.numpy()
        if hasattr(audio_chunk, "tolist"):
            audio_chunk = audio_chunk.tolist()

        pcm_samples = array("h")
        for sample in self._flatten_samples(audio_chunk):
            normalized = max(-1.0, min(1.0, float(sample)))
            pcm_samples.append(int(normalized * 32767))
        return pcm_samples

    def _flatten_samples(self, samples: Any) -> Any:
        if isinstance(samples, (list, tuple)):
            for sample in samples:
                if isinstance(sample, (list, tuple)):
                    yield from self._flatten_samples(sample)
                else:
                    yield sample
            return

        yield samples

    def _write_wav(self, wav_path: Path, audio_samples: array) -> None:
        with wave.open(str(wav_path), "wb") as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(self.tts_sample_rate)
            wav_file.writeframes(audio_samples.tobytes())
