from src.swarm.swarmDTOs import MothershipResponseDTO

class Decoder:
    """
    The Final Decoder is the only component responsible for producing human-readable outputs.
    It takes the swarm's final response DTO and translates it
    into natural language text for the user.
    """

    def decode(self, response: MothershipResponseDTO) -> str:
        """
        Converts the final response DTO into a natural language response.
        """
        if not response:
            return "No reasoning output generated by the cognitive layer."

        if response.decision:
            return response.decision

        if response.reasoning_summary:
            return response.reasoning_summary

        return "I am processing the sensory inputs but did not formulate a final thought."
