from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class ScratchPad:
    """
    Temporary working memory of a single cognitive node.

    This object is recreated (or reset) for every thinking session.
    Nothing stored here is assumed to be permanent.
    """

    ##########################################################
    # Initial Inputs
    ##########################################################

    perception: Optional[Any] = None

    ##########################################################
    # Cognitive State
    ##########################################################

    retrieved_memories: List[Any] = field(default_factory=list)

    emotional_state: Optional[Any] = None

    ##########################################################
    # Thinking State
    ##########################################################

    thoughts: List[Any] = field(default_factory=list)

    intermediate_results: List[Any] = field(default_factory=list)

    hypotheses: List[Any] = field(default_factory=list)

    ##########################################################
    # Local Context
    ##########################################################

    context: Dict[str, Any] = field(default_factory=dict)

    ##########################################################
    # Final Local Decision
    ##########################################################

    decision: Optional[Any] = None

    confidence: float = 0.0

    ##########################################################
    # Lifecycle Methods
    ##########################################################

    def initialize(
        self,
        perception: Any,
        memory: List[Any],
        emotion: Any
    ) -> None:
        """
        Initializes the scratchpad for a new thinking session.
        """
        self.perception = perception
        self.retrieved_memories = memory
        self.emotional_state = emotion

    def append_thought(self, thought: Any) -> None:
        """
        Adds one reasoning step generated by the decoder.
        """
        self.thoughts.append(thought)

    def add_hypothesis(self, hypothesis: Any) -> None:
        self.hypotheses.append(hypothesis)

    def add_intermediate_result(self, result: Any) -> None:
        self.intermediate_results.append(result)

    def update_context(
        self,
        key: str,
        value: Any
    ) -> None:
        """
        Stores arbitrary temporary information.
        """
        self.context[key] = value

    ##########################################################
    # Read Methods
    ##########################################################

    def current_context(self) -> Dict[str, Any]:
        """
        Returns everything currently known by the node.

        This object is what will be sent to the decoder during
        a single reasoning iteration.
        """
        return {
            "perception": self.perception,
            "memory": self.retrieved_memories,
            "emotion": self.emotional_state,
            "thoughts": self.thoughts,
            "hypotheses": self.hypotheses,
            "intermediate_results": self.intermediate_results,
            "context": self.context,
        }

    ##########################################################
    # Decision Methods
    ##########################################################

    def set_decision(
        self,
        decision: Any,
        confidence: float
    ) -> None:
        self.decision = decision
        self.confidence = confidence

    def final_state(self) -> Dict[str, Any]:
        """
        Returns the complete cognitive state of the node.
        """
        return {
            "decision": self.decision,
            "confidence": self.confidence,
            "thoughts": self.thoughts,
            "memory": self.retrieved_memories,
            "emotion": self.emotional_state,
            "context": self.context,
        }

    ##########################################################
    # Reset
    ##########################################################

    def clear(self) -> None:
        """
        Clears the working memory after processing finishes.
        """
        self.perception = None
        self.retrieved_memories.clear()
        self.emotional_state = None
        self.thoughts.clear()
        self.hypotheses.clear()
        self.intermediate_results.clear()
        self.context.clear()
        self.decision = None
        self.confidence = 0.0
