import os
import sys

# Silence HuggingFace progress bars and warning logs globally before any HF imports occur
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

import logging
import asyncio
import argparse
from typing import Optional

# Setup base logging
logging.basicConfig(level=logging.WARNING, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("shiva.cli")

from src.brain.memory.MemoryEngine import MemoryEngine
from src.brain.emotionalHandlerAndStore.Homeostasis import Homeostasis
from src.brain.node.nodeProcessingEngine import ReasoningScheduler
from src.swarm.mothership import Mothership

from src.output.voice import VoiceGenerator
from src.brain.transformer.thought_parser import parse_thought_text


class FallbackEmotionHandler:
    """Minimal emotion adapter used when model-backed emotion components cannot load."""

    def __init__(self, homeostasis_engine: Homeostasis, memory_engine: MemoryEngine):
        self._homeostasis = homeostasis_engine
        self._memory = memory_engine

    def perceive_event(self, event):
        self._memory.store(
            perception=event,
            emotion=None,
            homeostasis=self._homeostasis.current_state(),
            context={"source": "fallback_emotion"},
        )
        return None

    def current_emotion(self):
        return None

    def current_homeostasis(self):
        return self._homeostasis.current_state()


class FallbackDecoder:
    """Deterministic decoder that preserves CLI behavior without ML dependencies."""

    def generateDecision(self, context, **kwargs):
        perception = self._extract_query(str(context.perception))
        if len(perception) > 500:
            perception = f"{perception[:497]}..."

        raw_text = (
            "THOUGHT: Model-backed reasoning is unavailable, so this response is generated by the "
            "deterministic CLI fallback.\n"
            "CRITIQUE: Install the ML dependencies and local model weights for full cognitive reasoning.\n"
            "CONFIDENCE: 0.35\n"
            f"DECISION: Unable to run model-backed reasoning locally. Received input: {perception}"
        )
        return parse_thought_text(raw_text)

    def _extract_query(self, perception: str) -> str:
        for line in perception.splitlines():
            if line.startswith("Query:"):
                return " ".join(line.removeprefix("Query:").split())
        return " ".join(perception.split())

def initialize_cognitive_core() -> Mothership:
    """Assembles the swarm cognitive core components."""
    # 1. Initialize Memory Engine
    memory_engine = MemoryEngine()

    # 2. Initialize Homeostasis
    homeostasis = Homeostasis()

    try:
        from src.brain.emotionalHandlerAndStore.emotionHandlerAndOrchestrator import EmotionalOrchestrator
        from src.brain.emotionalHandlerAndStore.AppraisalEngine import (
            AppraisalEngine,
            FeatureExtractor,
            FTTransformerFeatureEmbedding,
            CognitiveStateEncoder,
            AppraisalNetwork,
            TransformerConfig,
        )
        from src.brain.emotionalHandlerAndStore.EmotionDynamicsEngine import (
            EmotionDynamicsEngine,
            EmotionInputBuilder,
            EmotionEmbedding,
            EmotionModel,
            EmotionGenerator,
        )

        extractor = FeatureExtractor()
        embedding = FTTransformerFeatureEmbedding()
        config = TransformerConfig()
        config.vector_size = embedding.vector_size
        encoder = CognitiveStateEncoder(config=config)
        network = AppraisalNetwork(vector_size=embedding.vector_size)
        appraisal_engine = AppraisalEngine(extractor, embedding, encoder, network)

        input_builder = EmotionInputBuilder()
        emotion_embedding = EmotionEmbedding()
        emotion_model = EmotionModel()
        emotion_generator = EmotionGenerator()
        emotion_dynamics_engine = EmotionDynamicsEngine(
            input_builder, emotion_embedding, emotion_model, emotion_generator
        )

        emotion_handler = EmotionalOrchestrator(
            appraisal_engine=appraisal_engine,
            emotion_engine=emotion_dynamics_engine,
            homeostasis_engine=homeostasis,
            memory_engine=memory_engine,
        )
    except Exception as exc:
        logger.warning("Using fallback emotion handler: %s", exc)
        emotion_handler = FallbackEmotionHandler(homeostasis, memory_engine)

    try:
        from src.brain.transformer.Decoder import Decoder as TransformerDecoder
        transformer_decoder = TransformerDecoder()
    except Exception as exc:
        logger.warning("Using fallback decoder: %s", exc)
        transformer_decoder = FallbackDecoder()

    scheduler = ReasoningScheduler(transformer_decoder)

    mothership = Mothership(
        memory_engine=memory_engine,
        emotion_handler=emotion_handler,
        scheduler=scheduler,
        execution_engine=None
    )
    return mothership

async def handle_voice_input(prompt_queue: asyncio.Queue):
    """Starts a local WebSocket server to receive voice transcription streams."""
    try:
        import websockets
        import json
    except ImportError:
        print("[Voice Input] Error: websockets library is required for --voice-in command.")
        return None

    async def handler(websocket):
        print("\n[Voice Input] Web client connected to transcription gateway.")
        try:
            async for message in websocket:
                try:
                    data = json.loads(message)
                    transcription = data.get("text", "")
                except json.JSONDecodeError:
                    transcription = str(message)
                
                if transcription.strip():
                    await prompt_queue.put(transcription)
        except Exception as e:
            logger.debug(f"Voice WS Exception: {e}")
        finally:
            print("[Voice Input] Web client disconnected.")

    # Start WebSocket server on local port 8765
    server = await websockets.serve(handler, "localhost", 8765)
    print("\n[Voice Input] WebSocket server active on ws://localhost:8765")
    print("[Voice Input] Speak into your connected transcriber to send prompts to Shiva...")
    return server

def print_banner():
    print("""
===================================================
                  S H I V A
         Autonomous Cognitive Swarm Engine
===================================================
""")

def run_query(mothership: Mothership, query: str, workspace_path: Optional[str], voice_out: bool):
    """Executes a single reasoning query on the Mothership."""
    if workspace_path:
        mothership.set_workspace(workspace_path)
    
    print("\n[Shiva Swarm] Thinking...")
    response = mothership.solve_problem(query)
    
    print("\n================ DECISION ================")
    print(response.decision)
    print("===========================================")
    print(f"Confidence: {response.confidence:.2%}")
    print(f"Cycles run: {response.cycles_used}")
    
    if voice_out:
        print("\n[Voice Output] Generating spoken response...")
        voice = VoiceGenerator()
        output_file = "shiva_output.wav"
        success = voice.synthesize(response.decision, output_file)
        if success:
            print(f"[Voice Output] Audio synthesis completed. Saved to: {os.path.abspath(output_file)}")
        else:
            print("[Voice Output] Failed to synthesize audio output.")

async def main_async():
    parser = argparse.ArgumentParser(description="Shiva CLI - B2B Cognitive Swarm Engine")
    parser.add_argument("-q", "--query", type=str, help="Submit a single raw text prompt to the swarm.")
    parser.add_argument("-d", "--dir", type=str, help="Target project workspace folder to inspect/hook.")
    parser.add_argument("-v", "--voice-out", action="store_true", help="Convert the final text output to voice WAV.")
    parser.add_argument("-i", "--interactive", action="store_true", help="Run in an interactive terminal session.")
    parser.add_argument("--voice-in", action="store_true", help="Open a WebSocket server on ws://localhost:8765 to receive voice-to-text inputs.")

    args = parser.parse_args()

    if not any([args.query, args.interactive, args.voice_in]):
        parser.print_help()
        sys.exit(1)

    print_banner()
    print("[Shiva System] Loading cognitive layers and weights...")
    mothership = initialize_cognitive_core()
    print("[Shiva System] Core initialized successfully.")

    if args.dir:
        mothership.set_workspace(args.dir)

    # 1. Single execution mode
    if args.query:
        run_query(mothership, args.query, args.dir, args.voice_out)
        return

    # 2. Voice WebSocket input mode
    if args.voice_in:
        prompt_queue = asyncio.Queue()
        server = await handle_voice_input(prompt_queue)
        
        if server:
            try:
                while True:
                    # Enter dream state while waiting for incoming voice prompts
                    mothership.enter_dream_state()
                    prompt = await prompt_queue.get()
                    print(f"\n[Voice Input Prompt Received]: '{prompt}'")
                    run_query(mothership, prompt, args.dir, args.voice_out)
            except KeyboardInterrupt:
                pass
            finally:
                mothership.exit_dream_state()
                server.close()
                await server.wait_closed()
        return

    # 3. Interactive REPL mode
    if args.interactive:
        print("\nShiva Interactive Prompt Session. Type 'exit' or 'quit' to close.")
        try:
            while True:
                # Enter dream state while waiting for user text inputs
                mothership.enter_dream_state()
                try:
                    prompt = input("\nshiva> ").strip()
                except (KeyboardInterrupt, EOFError):
                    print("\nExiting Shiva session.")
                    break
                
                if not prompt:
                    continue
                if prompt.lower() in ("exit", "quit"):
                    break
                run_query(mothership, prompt, args.dir, args.voice_out)
        finally:
            mothership.exit_dream_state()

def main():
    asyncio.run(main_async())

if __name__ == "__main__":
    main()
